name: Lint Codebase

on:
  push:
    branches:
      - main
      - develop # Or any other branches you want to trigger on
  pull_request:
    branches:
      - main
      - develop # Or any other branches you want to target

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install ruff
          # If you have other dependencies needed for linting (e.g., plugins for ruff)
          # pip install -r requirements.txt # or based on your pyproject.toml

      - name: Run Ruff Linter
        run: ruff check .

      # Optional: Add ruff format check if you want to enforce formatting
      # - name: Run Ruff Formatter Check
      #   run: ruff format --check .
